# Generated by Django 4.1.10 on 2023-11-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv_files/")),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_content", models.TextField()),
                ("api_result", models.TextField(default="")),
                (
                    "csv_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_textsentiment.csvfile",
                    ),
                ),
            ],
        ),
    ]
