# Generated by Django 4.1.10 on 2023-11-21 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_textsentiment", "0003_apiresponse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIResponse",
        ),
    ]
