# Generated by Django 4.1.10 on 2023-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClothDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cloth_ID", models.IntegerField()),
                ("Age", models.IntegerField()),
                ("Review_Text", models.CharField(max_length=255)),
                ("Rating", models.IntegerField()),
                ("Positive_Feedback_Count", models.IntegerField()),
                ("Department_Name", models.CharField(max_length=255)),
            ],
        ),
    ]
