# Generated by Django 4.1.10 on 2023-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlipkartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.TextField()),
                ("product_price", models.IntegerField()),
                ("rate", models.IntegerField()),
                ("review", models.TextField()),
                ("summary", models.TextField()),
                ("sentiment", models.TextField()),
            ],
        ),
    ]
