# Generated by Django 4.1.10 on 2023-11-07 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_reports", "0002_flipkartproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlipkartProduct",
        ),
        migrations.RemoveField(
            model_name="clothdescription",
            name="Positive_Feedback_Count",
        ),
    ]
